export const strings = {
  en: {
    shoppingList: 'Shopping List',
    inventory: 'Things we have!',
    addItem: 'Add item...',
    noItems: 'Your list is empty. Add something above!',
    clearChecked: (n) => `Clear ${n} item${n > 1 ? 's' : ''}`,
    removeChecked: (n) => `Remove ${n} item${n > 1 ? 's' : ''}?`,
    cancel: 'Cancel',
    clear: 'Clear',
    noInventory: 'No items yet. Tap + to add something.',
    addItemTitle: 'Add Item',
    editItemTitle: 'Edit Item',
    itemName: 'Item name',
    category: 'Category',
    save: 'Save',
    categories: {
      Fridge: 'Fridge',
      Freezer: 'Freezer',
      Pantry: 'Pantry',
    },
  },
  no: {
    shoppingList: 'Handleliste',
    inventory: 'Ting vi har!',
    addItem: 'Legg til vare...',
    noItems: 'Listen er tom. Legg til noe ovenfor!',
    clearChecked: (n) => `Fjern ${n} vare${n > 1 ? 'r' : ''}`,
    removeChecked: (n) => `Fjerne ${n} vare${n > 1 ? 'r' : ''}?`,
    cancel: 'Avbryt',
    clear: 'Fjern',
    noInventory: 'Ingen varer ennå. Trykk + for å legge til.',
    addItemTitle: 'Legg til vare',
    editItemTitle: 'Rediger vare',
    itemName: 'Varenavn',
    category: 'Kategori',
    save: 'Lagre',
    categories: {
      Fridge: 'Kjøleskap',
      Freezer: 'Fryser',
      Pantry: 'Tørrvare',
    },
  },
  sv: {
    shoppingList: 'Inköpslista',
    inventory: 'Saker vi har!',
    addItem: 'Lägg till vara...',
    noItems: 'Listan är tom. Lägg till något ovanför!',
    clearChecked: (n) => `Rensa ${n} vara${n > 1 ? 'r' : ''}`,
    removeChecked: (n) => `Ta bort ${n} vara${n > 1 ? 'r' : ''}?`,
    cancel: 'Avbryt',
    clear: 'Rensa',
    noInventory: 'Inga varor ännu. Tryck + för att lägga till.',
    addItemTitle: 'Lägg till vara',
    editItemTitle: 'Redigera vara',
    itemName: 'Varenamn',
    category: 'Kategori',
    save: 'Spara',
    categories: {
      Fridge: 'Kyl',
      Freezer: 'Frys',
      Pantry: 'Skafferi',
    },
  },
  da: {
    shoppingList: 'Indkøbsliste',
    inventory: 'Ting vi har!',
    addItem: 'Tilføj vare...',
    noItems: 'Listen er tom. Tilføj noget ovenfor!',
    clearChecked: (n) => `Fjern ${n} vare${n > 1 ? 'r' : ''}`,
    removeChecked: (n) => `Fjern ${n} vare${n > 1 ? 'r' : ''}?`,
    cancel: 'Annuller',
    clear: 'Fjern',
    noInventory: 'Ingen varer endnu. Tryk + for at tilføje.',
    addItemTitle: 'Tilføj vare',
    editItemTitle: 'Rediger vare',
    itemName: 'Varenavn',
    category: 'Kategori',
    save: 'Gem',
    categories: {
      Fridge: 'Køleskab',
      Freezer: 'Fryser',
      Pantry: 'Skafferi',
    },
  },
};