export const strings = {
  en: {
    shoppingList: 'Shopping List',
    inventory: 'Things we have!',
    addItem: 'Add item...',
    noItems: 'Your list is empty. Add something above!',
    clearChecked: (n) => `Clear ${n} checked item${n > 1 ? 's' : ''}`,
    removeChecked: (n) => `Remove ${n} checked item${n > 1 ? 's' : ''}?`,
    cancel: 'Cancel',
    clear: 'Clear',
    noInventory: 'No items yet. Tap + to add something.',
    addItemTitle: 'Add Item',
    editItemTitle: 'Edit Item',
    itemName: 'Item name',
    category: 'Category',
    save: 'Save',
    categories: {
      Fridge: 'Fridge',
      Freezer: 'Freezer',
      Pantry: 'Pantry',
    },
  },
  no: {
    shoppingList: 'Handleliste',
    inventory: 'Ting vi har!',
    addItem: 'Legg til vare...',
    noItems: 'Listen er tom. Legg til noe ovenfor!',
    clearChecked: (n) => `Fjern ${n} avkrysset vare${n > 1 ? 'r' : ''}`,
    removeChecked: (n) => `Fjerne ${n} avkrysset vare${n > 1 ? 'r' : ''}?`,
    cancel: 'Avbryt',
    clear: 'Fjern',
    noInventory: 'Ingen varer ennå. Trykk + for å legge til.',
    addItemTitle: 'Legg til vare',
    editItemTitle: 'Rediger vare',
    itemName: 'Varenavn',
    category: 'Kategori',
    save: 'Lagre',
    categories: {
      Fridge: 'Kjøleskap',
      Freezer: 'Fryser',
      Pantry: 'Tørrvare',
    },
  },
};